line 1:7 missing ')' at 'a'
line 1:14 token recognition error at: '['
line 1:17 token recognition error at: ']'
line 2:3 token recognition error at: '['
line 2:5 token recognition error at: ']'
line 2:10 token recognition error at: '['
line 2:12 token recognition error at: ']'
line 6:7 token recognition error at: ','
line 6:8 extraneous input 'c' expecting ':'
line 6:16 token recognition error at: '['
line 6:11 missing 'int' at 'array'
line 6:19 token recognition error at: ']'
line 7:8 token recognition error at: '['
line 7:10 token recognition error at: ']'
line 7:9 extraneous input '5' expecting ';'
line 8:3 token recognition error at: '['
line 8:4 no viable alternative at input 'c7'
line 8:5 token recognition error at: ']'
line 8:10 token recognition error at: '['
line 8:12 token recognition error at: ']'
